# Projet Kayak — Partie 1 : Récupération de la météo

**Objectif :** pour une liste de 35 villes touristiques françaises, récupérer :
1. Les coordonnées géographiques (latitude / longitude) via l'API **Nominatim** (OpenStreetMap) — gratuite, sans clé.
2. Les prévisions météo sur 5 jours via l'API **OpenWeatherMap** — gratuite, nécessite une clé API.

On en déduira ensuite un **score météo** par ville pour identifier les destinations les plus ensoleillées de la semaine à venir.

## 1. Imports et configuration

In [1]:
%pip install python-dotenv plotly scrapy boto3 sqlalchemy psycopg2-binary

Requirement already satisfied: python-dotenv in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (1.2.2)
Requirement already satisfied: plotly in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (5.24.1)
Requirement already satisfied: scrapy in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (2.16.0)
Requirement already satisfied: boto3 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (1.43.12)
Requirement already satisfied: sqlalchemy in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (2.9.12)
Requirement already satisfied: tenacity>=6.2.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from plotly) (26.2)
Requirement already satisfied: cryptography>=37.0.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (48.0.0)
Requirement already satisfied: cssselect>=0.9.1 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (1.4.0)
Requirement already satisfied: defusedxml>=0.7.1 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (0.7.1)
Requirement already satisfied: itemadapter>=0.1.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (0.13.1)
Requirement already satisfied: itemloaders>=1.0.1 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (1.4.0)
Requirement already satisfied: lxml>=4.6.4 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (6.1.1)
Requirement already satisfied: parsel>=1.5.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (1.11.0)
Requirement already satisfied: protego>=0.1.15 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (0.6.0)
Requirement already satisfied: pydispatcher>=2.0.5 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (2.0.7)
Requirement already satisfied: pyopenssl>=22.0.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (26.2.0)
Requirement already satisfied: queuelib>=1.4.2 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (1.9.0)
Requirement already satisfied: service-identity>=23.1.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (24.2.0)
Requirement already satisfied: tldextract in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (5.3.1)
Requirement already satisfied: twisted>=21.7.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (26.4.0)
Requirement already satisfied: w3lib>=1.17.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (2.4.1)
Requirement already satisfied: zope-interface>=5.1.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from scrapy) (8.4)
Requirement already satisfied: botocore<1.44.0,>=1.43.12 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from boto3) (1.43.12)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from boto3) (1.1.0)
Requirement already satisfied: s3transfer<0.18.0,>=0.17.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from boto3) (0.17.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from botocore<1.44.0,>=1.43.12->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from botocore<1.44.0,>=1.43.12->boto3) (2.7.0)
Requirement already satisfied: six>=1.5 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.12->boto3) (1.17.0)
Requirement already satisfied: greenlet>=1 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from cryptography>=37.0.0->scrapy) (2.0.0)
Requirement already satisfied: pycparser in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from cffi>=2.0.0->cryptography>=37.0.0->scrapy) (3.0)
Requirement already satisfied: attrs>=19.1.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from service-identity>=23.1.0->scrapy) (26.1.0)
Requirement already satisfied: pyasn1 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from service-identity>=23.1.0->scrapy) (0.6.3)
Requirement already satisfied: pyasn1-modules in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from service-identity>=23.1.0->scrapy) (0.4.2)
Requirement already satisfied: automat>=24.8.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from twisted>=21.7.0->scrapy) (25.4.16)
Requirement already satisfied: constantly>=15.1 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from twisted>=21.7.0->scrapy) (23.10.4)
Requirement already satisfied: hyperlink>=17.1.1 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from twisted>=21.7.0->scrapy) (21.0.0)
Requirement already satisfied: incremental>=24.7.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from twisted>=21.7.0->scrapy) (24.11.0)
Requirement already satisfied: idna>=2.5 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from hyperlink>=17.1.1->twisted>=21.7.0->scrapy) (3.15)
Requirement already satisfied: requests>=2.1.0 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from tldextract->scrapy) (2.34.2)
Requirement already satisfied: requests-file>=1.4 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from tldextract->scrapy) (3.0.1)
Requirement already satisfied: filelock>=3.0.8 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from tldextract->scrapy) (3.29.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from requests>=2.1.0->tldextract->scrapy) (3.4.7)
Requirement already satisfied: certifi>=2023.5.7 in c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages (from requests>=2.1.0->tldextract->scrapy) (2026.5.20)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~lotly (c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages)
WARNING: Ignoring invalid distribution ~lotly (c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages)
WARNING: Ignoring invalid distribution ~lotly (c:\dev\Projets_Certif\.venv-jedha\Lib\site-packages)

In [2]:
import os
import time
import requests
import pandas as pd
from dotenv import load_dotenv

# On charge la clé API OpenWeatherMap depuis un fichier .env (jamais commit sur git)
# Le fichier .env doit contenir une ligne : OWM_API_KEY=ta_cle_ici
load_dotenv()
OWM_API_KEY = os.getenv("OWM_API_KEY")

assert OWM_API_KEY, "Clé API OpenWeatherMap manquante — vérifie ton fichier .env"

## 2. Liste des 35 villes cibles

Liste fournie par l'énoncé du projet.

In [3]:
cities = [
    "Mont Saint Michel", "Saint Malo", "Bayeux", "Le Havre", "Rouen",
    "Paris", "Amiens", "Lille", "Strasbourg", "Chateau du Haut Koenigsbourg",
    "Colmar", "Eguisheim", "Besancon", "Dijon", "Annecy",
    "Grenoble", "Lyon", "Gorges du Verdon", "Bormes les Mimosas", "Cassis",
    "Marseille", "Aix en Provence", "Avignon", "Uzes", "Nimes",
    "Aigues Mortes", "Saintes Maries de la mer", "Collioure", "Carcassonne", "Ariege",
    "Toulouse", "Montauban", "Biarritz", "Bayonne", "La Rochelle"
]

print(f"Nombre de villes : {len(cities)}")

Nombre de villes : 35

## 3. Géocoding avec Nominatim

Nominatim est l'API de géocodage d'OpenStreetMap. Elle est **gratuite et sans clé**, mais impose deux règles :
- Un `User-Agent` personnalisé (sinon la requête est refusée).
- **Maximum 1 requête par seconde** (politique d'utilisation).

On définit une fonction qui prend le nom d'une ville et renvoie un dict `{city, lat, lon}`.

In [4]:
NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"
HEADERS = {"User-Agent": "KayakProject/1.0 (projet etudiant)"}

def geocode(city: str) -> dict:
    """Retourne lat/lon pour une ville française via Nominatim."""
    params = {
        "q": f"{city}, France",  # on précise France pour éviter les homonymes
        "format": "json",
        "limit": 1,                # on ne garde que le premier résultat
    }
    response = requests.get(NOMINATIM_URL, params=params, headers=HEADERS, timeout=10)
    response.raise_for_status()
    results = response.json()
    print(type(results))   # list -> Nominatim renvoie un tableau JSON de résultats 
    print(results)         # renvoie tout le résultat (ici toutes les infos concernant Paris quand on appelle la fonction avec Paris)
    if not results:        # fonctionne exactement comme un if / else, grâce à un mécanisme qu'on appelle le early return (retour anticipé)
        return {"city": city, "lat": None, "lon": None}
    return {
        "city": city,      # renvoie un dictionnaire avec simplement ce dont on a besoin, i.e. ville, lat, long
        "lat": float(results[0]["lat"]),
        "lon": float(results[0]["lon"]),
    }

# Test sur une ville
geocode("Paris")

<class 'list'>
[{'place_id': 98427244, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 7444, 'lat': '48.8588897', 'lon': '2.3200410', 'class': 'boundary', 'type': 'administrative', 'place_rank': 15, 'importance': 0.897098092136026, 'addresstype': 'suburb', 'name': 'Paris', 'display_name': 'Paris, Île-de-France, France métropolitaine, France', 'boundingbox': ['48.8155755', '48.9021560', '2.2241220', '2.4697602']}]

{'city': 'Paris', 'lat': 48.8588897, 'lon': 2.320041}

In [5]:
# On boucle sur toutes les villes en respectant le rate limit (1 req/sec)
coords = []
for city in cities:     # cities est la liste des 35 villes référencées plus haut 
    coords.append(geocode(city))
    time.sleep(1)       # indispensable pour ne pas se faire bannir

df_coords = pd.DataFrame(coords)
df_coords

<class 'list'>
[{'place_id': 281361808, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'way', 'osm_id': 211285890, 'lat': '48.6359541', 'lon': '-1.5114600', 'class': 'place', 'type': 'islet', 'place_rank': 20, 'importance': 0.4711675122514022, 'addresstype': 'islet', 'name': 'Mont Saint-Michel', 'display_name': 'Mont Saint-Michel, Le Mont-Saint-Michel, Avranches, Manche, Normandie, France métropolitaine, 50170, France', 'boundingbox': ['48.6349172', '48.6370310', '-1.5133292', '-1.5094796']}]
<class 'list'>
[{'place_id': 284162046, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 905534, 'lat': '48.6495180', 'lon': '-2.0260409', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6250994319975981, 'addresstype': 'town', 'name': 'Saint-Malo', 'display_name': 'Saint-Malo, Ille-et-Vilaine, Bretagne, France métropolitaine, 35400, France', 'boundingbox': ['48.5979853', '48.6949736', '-2.0765246', '-1.9367259']}]
<class 'list'>
[{'place_id': 280655053, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 145776, 'lat': '49.2764624', 'lon': '-0.7024738', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6124001184225292, 'addresstype': 'town', 'name': 'Bayeux', 'display_name': 'Bayeux, Calvados, Normandie, France métropolitaine, 14400, France', 'boundingbox': ['49.2608110', '49.2934736', '-0.7275523', '-0.6757378']}]
<class 'list'>
[{'place_id': 99236296, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 104492, 'lat': '49.4938975', 'lon': '0.1079732', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6784794831885882, 'addresstype': 'city', 'name': 'Le Havre', 'display_name': 'Le Havre, Seine-Maritime, Normandie, France métropolitaine, France', 'boundingbox': ['49.4516697', '49.5401463', '0.0667992', '0.1955556']}]
<class 'list'>
[{'place_id': 99070671, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 75628, 'lat': '49.4404591', 'lon': '1.0939658', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6944913621565563, 'addresstype': 'city', 'name': 'Rouen', 'display_name': 'Rouen, Seine-Maritime, Normandie, France métropolitaine, France', 'boundingbox': ['49.4172001', '49.4652601', '1.0300648', '1.1521157']}]
<class 'list'>
[{'place_id': 98427244, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 7444, 'lat': '48.8588897', 'lon': '2.3200410', 'class': 'boundary', 'type': 'administrative', 'place_rank': 15, 'importance': 0.897098092136026, 'addresstype': 'suburb', 'name': 'Paris', 'display_name': 'Paris, Île-de-France, France métropolitaine, France', 'boundingbox': ['48.8155755', '48.9021560', '2.2241220', '2.4697602']}]
<class 'list'>
[{'place_id': 99515658, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 114347, 'lat': '49.8941708', 'lon': '2.2956951', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6748456365793974, 'addresstype': 'city', 'name': 'Amiens', 'display_name': 'Amiens, Somme, Hauts-de-France, France métropolitaine, 80000, France', 'boundingbox': ['49.8468370', '49.9505487', '2.2235574', '2.3457767']}]
<class 'list'>
[{'place_id': 102005298, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 58404, 'lat': '50.6365654', 'lon': '3.0635282', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.7054993931704441, 'addresstype': 'city', 'name': 'Lille', 'display_name': 'Lille, Nord, Hauts-de-France, France métropolitaine, France', 'boundingbox': ['50.6008363', '50.6612596', '2.9679677', '3.1257250']}]
<class 'list'>
[{'place_id': 120717819, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 71033, 'lat': '48.5846140', 'lon': '7.7507127', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.7372988337549014, 'addresstype': 'city', 'name': 'Strasbourg', 'display_name': "Strasbourg, Bas-Rhin, Collectivité européenne d'Alsace, Grand Est, France métropolitaine, France", 'boundingbox': ['48.4919357', '48.6461896', '7.6881371', '7.8360646']}]
<class 'list'>
[{'place_id': 121042783, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'way', 'osm_id': 1299451538, 'lat': '48.2493820', 'lon': '7.3439412', 'class': 'historic', 'type': 'castle', 'place_rank': 30, 'importance': 0.3697233328141787, 'addresstype': 'historic', 'name': 'Château du Haut-Kœnigsbourg', 'display_name': "Château du Haut-Kœnigsbourg, D 159, Schaflager, Orschwiller, Sélestat-Erstein, Bas-Rhin, Collectivité européenne d'Alsace, Grand Est, France métropolitaine, 67600, France", 'boundingbox': ['48.2490104', '48.2497566', '7.3424818', '7.3461306']}]
<class 'list'>
[{'place_id': 121164431, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 61423, 'lat': '48.0777517', 'lon': '7.3579641', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6305771963242904, 'addresstype': 'town', 'name': 'Colmar', 'display_name': "Colmar, Colmar-Ribeauvillé, Haut-Rhin, Collectivité européenne d'Alsace, Grand Est, France métropolitaine, 68000, France", 'boundingbox': ['48.0407053', '48.1820620', '7.3154803', '7.4691670']}]
<class 'list'>
[{'place_id': 121333649, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 79442, 'lat': '48.0447968', 'lon': '7.3079618', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.5685129455465597, 'addresstype': 'village', 'name': 'Eguisheim', 'display_name': "Eguisheim, Colmar-Ribeauvillé, Haut-Rhin, Collectivité européenne d'Alsace, Grand Est, France métropolitaine, 68420, France", 'boundingbox': ['48.0240327', '48.0515072', '7.2412792', '7.3518540']}]
<class 'list'>
[{'place_id': 92553994, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 103599, 'lat': '47.2380222', 'lon': '6.0243622', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6642998857990005, 'addresstype': 'city', 'name': 'Besançon', 'display_name': 'Besançon, Doubs, Bourgogne-Franche-Comté, France métropolitaine, 25000, France', 'boundingbox': ['47.2006872', '47.3200746', '5.9409668', '6.0835059']}]
<class 'list'>
[{'place_id': 93940430, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 74090, 'lat': '47.3215806', 'lon': '5.0414701', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6839073216875784, 'addresstype': 'city', 'name': 'Dijon', 'display_name': "Dijon, Côte-d'Or, Bourgogne-Franche-Comté, France métropolitaine, 21000, France", 'boundingbox': ['47.2862467', '47.3774741', '4.9624434', '5.1020598']}]
<class 'list'>
[{'place_id': 88762115, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 6791758, 'lat': '45.8992348', 'lon': '6.1288847', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6280772037744516, 'addresstype': 'city', 'name': 'Annecy', 'display_name': 'Annecy, Haute-Savoie, Auvergne-Rhône-Alpes, France métropolitaine, France', 'boundingbox': ['45.8280024', '45.9766928', '6.0484121', '6.2043932']}]
<class 'list'>
[{'place_id': 89646215, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 80348, 'lat': '45.1875602', 'lon': '5.7357819', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6939776315266458, 'addresstype': 'city', 'name': 'Grenoble', 'display_name': 'Grenoble, Isère, Auvergne-Rhône-Alpes, France métropolitaine, France', 'boundingbox': ['45.1541442', '45.2140762', '5.6776059', '5.7531315']}]
<class 'list'>
[{'place_id': 90160981, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 120965, 'lat': '45.7578137', 'lon': '4.8320114', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.7489604368049191, 'addresstype': 'city', 'name': 'Lyon', 'display_name': 'Lyon, Métropole de Lyon, Rhône, Auvergne-Rhône-Alpes, France métropolitaine, France', 'boundingbox': ['45.7073666', '45.8082628', '4.7718132', '4.8984245']}]
<class 'list'>
[{'place_id': 82363223, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'node', 'osm_id': 7193513219, 'lat': '43.7496562', 'lon': '6.3285616', 'class': 'natural', 'type': 'gorge', 'place_rank': 22, 'importance': 0.39635455236634, 'addresstype': 'gorge', 'name': 'Gorges du Verdon', 'display_name': "Gorges du Verdon, La Palud-sur-Verdon, Castellane, Alpes-de-Haute-Provence, Provence-Alpes-Côte d'Azur, France métropolitaine, 04120, France", 'boundingbox': ['43.7496062', '43.7497062', '6.3285116', '6.3286116']}]
<class 'list'>
[{'place_id': 82947484, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 1118915, 'lat': '43.1506968', 'lon': '6.3419285', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.5172954756534932, 'addresstype': 'village', 'name': 'Bormes-les-Mimosas', 'display_name': "Bormes-les-Mimosas, Toulon, Var, Provence-Alpes-Côte d'Azur, France métropolitaine, 83230, France", 'boundingbox': ['43.0864135', '43.2278201', '6.2716142', '6.4514893']}]
<class 'list'>
[{'place_id': 83452381, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 76425, 'lat': '43.2140359', 'lon': '5.5396318', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.5189517291632535, 'addresstype': 'village', 'name': 'Cassis', 'display_name': "Cassis, Marseille, Bouches-du-Rhône, Provence-Alpes-Côte d'Azur, France métropolitaine, 13260, France", 'boundingbox': ['43.1884732', '43.2487231', '5.5063193', '5.5945199']}]
<class 'list'>
[{'place_id': 82966111, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 76469, 'lat': '43.2963986', 'lon': '5.3777888', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.7414985565519032, 'addresstype': 'city', 'name': 'Marseille', 'display_name': "Marseille, Bouches-du-Rhône, Provence-Alpes-Côte d'Azur, France métropolitaine, France", 'boundingbox': ['43.1696228', '43.3910329', '5.2287864', '5.5324758']}]
<class 'list'>
[{'place_id': 83161830, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 70279, 'lat': '43.5298424', 'lon': '5.4474738', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6449733583211327, 'addresstype': 'city', 'name': 'Aix-en-Provence', 'display_name': "Aix-en-Provence, Bouches-du-Rhône, Provence-Alpes-Côte d'Azur, France métropolitaine, France", 'boundingbox': ['43.4461058', '43.6259224', '5.2694745', '5.5063013']}]
<class 'list'>
[{'place_id': 82636973, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 102478, 'lat': '43.9492493', 'lon': '4.8059012', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6737176436675905, 'addresstype': 'city', 'name': 'Avignon', 'display_name': "Avignon, Vaucluse, Provence-Alpes-Côte d'Azur, France métropolitaine, 84000, France", 'boundingbox': ['43.8873819', '43.9967419', '4.7396309', '4.9271468']}]
<class 'list'>
[{'place_id': 87602259, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 380050, 'lat': '44.0121279', 'lon': '4.4196718', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.5757292410230347, 'addresstype': 'village', 'name': 'Uzès', 'display_name': 'Uzès, Nîmes, Gard, Occitanie, France métropolitaine, 30700, France', 'boundingbox': ['43.9811093', '44.0765914', '4.3852299', '4.4467859']}]
<class 'list'>
[{'place_id': 82204290, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 378685, 'lat': '43.8374249', 'lon': '4.3600687', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6544833695418243, 'addresstype': 'city', 'name': 'Nîmes', 'display_name': 'Nîmes, Gard, Occitanie, France métropolitaine, France', 'boundingbox': ['43.7412659', '43.9230177', '4.2356708', '4.4496605']}]
<class 'list'>
[{'place_id': 83121595, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 272287, 'lat': '43.5661521', 'lon': '4.1915400', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.5706786615523073, 'addresstype': 'town', 'name': 'Aigues-Mortes', 'display_name': 'Aigues-Mortes, Nîmes, Gard, Occitanie, France métropolitaine, 30220, France', 'boundingbox': ['43.4958113', '43.5920372', '4.0760703', '4.2442867']}]
<class 'list'>
[{'place_id': 84328318, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 414459, 'lat': '43.4515922', 'lon': '4.4277202', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.5100269773652484, 'addresstype': 'town', 'name': 'Saintes-Maries-de-la-Mer', 'display_name': "Saintes-Maries-de-la-Mer, Arles, Bouches-du-Rhône, Provence-Alpes-Côte d'Azur, France métropolitaine, 13460, France", 'boundingbox': ['43.4062445', '43.5858463', '4.2301364', '4.6444785']}]
<class 'list'>
[{'place_id': 84939196, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 18409, 'lat': '42.5250500', 'lon': '3.0831554', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.5495277624366346, 'addresstype': 'village', 'name': 'Collioure', 'display_name': 'Collioure, Céret, Pyrénées-Orientales, Occitanie, France métropolitaine, 66190, France', 'boundingbox': ['42.4832453', '42.5341084', '3.0495074', '3.0994238']}]
<class 'list'>
[{'place_id': 84898345, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 37774, 'lat': '43.2130358', 'lon': '2.3491069', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6329935644206688, 'addresstype': 'town', 'name': 'Carcassonne', 'display_name': 'Carcassonne, Aude, Occitanie, France métropolitaine, 11000, France', 'boundingbox': ['43.1713069', '43.2443707', '2.2615684', '2.4362676']}]
<class 'list'>
[{'place_id': 84734344, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 7439, 'lat': '42.9455368', 'lon': '1.4065544', 'class': 'boundary', 'type': 'administrative', 'place_rank': 12, 'importance': 0.6475948895014035, 'addresstype': 'county', 'name': 'Ariège', 'display_name': 'Ariège, Occitanie, France métropolitaine, France', 'boundingbox': ['42.5732416', '43.3162514', '0.8267506', '2.1758135']}]
<class 'list'>
[{'place_id': 85268269, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 35738, 'lat': '43.6044638', 'lon': '1.4442433', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.7287053511182572, 'addresstype': 'city', 'name': 'Toulouse', 'display_name': 'Toulouse, Haute-Garonne, Occitanie, France métropolitaine, France', 'boundingbox': ['43.5326969', '43.6687119', '1.3503311', '1.5153356']}]
<class 'list'>
[{'place_id': 85485907, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 137735, 'lat': '44.0175835', 'lon': '1.3549991', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6030130470327072, 'addresstype': 'town', 'name': 'Montauban', 'display_name': 'Montauban, Tarn-et-Garonne, Occitanie, France métropolitaine, 82000, France', 'boundingbox': ['43.9512579', '44.0922122', '1.2865419', '1.4427914']}]
<class 'list'>
[{'place_id': 288622853, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 166717, 'lat': '43.4832523', 'lon': '-1.5592776', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6233370780991901, 'addresstype': 'town', 'name': 'Biarritz', 'display_name': 'Biarritz, Bayonne, Pyrénées-Atlantiques, Nouvelle-Aquitaine, France métropolitaine, 64200, France', 'boundingbox': ['43.4475698', '43.4945381', '-1.5773906', '-1.5343915']}]
<class 'list'>
[{'place_id': 290541150, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 166713, 'lat': '43.4945144', 'lon': '-1.4736657', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6504282510940013, 'addresstype': 'town', 'name': 'Bayonne', 'display_name': 'Bayonne, Pyrénées-Atlantiques, Nouvelle-Aquitaine, France métropolitaine, 64100, France', 'boundingbox': ['43.4498733', '43.5188846', '-1.5048438', '-1.4172610']}]
<class 'list'>
[{'place_id': 289000003, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 117858, 'lat': '46.1597320', 'lon': '-1.1515951', 'class': 'boundary', 'type': 'administrative', 'place_rank': 16, 'importance': 0.6497530354817868, 'addresstype': 'city', 'name': 'La Rochelle', 'display_name': 'La Rochelle, Charente-Maritime, Nouvelle-Aquitaine, France métropolitaine, 17000, France', 'boundingbox': ['46.1331804', '46.1908971', '-1.2419231', '-1.1110970']}]

                            city        lat       lon
0              Mont Saint Michel  48.635954 -1.511460
1                     Saint Malo  48.649518 -2.026041
2                         Bayeux  49.276462 -0.702474
3                       Le Havre  49.493898  0.107973
4                          Rouen  49.440459  1.093966
5                          Paris  48.858890  2.320041
6                         Amiens  49.894171  2.295695
7                          Lille  50.636565  3.063528
8                     Strasbourg  48.584614  7.750713
9   Chateau du Haut Koenigsbourg  48.249382  7.343941
10                        Colmar  48.077752  7.357964
11                     Eguisheim  48.044797  7.307962
12                      Besancon  47.238022  6.024362
13                         Dijon  47.321581  5.041470
14                        Annecy  45.899235  6.128885
15                      Grenoble  45.187560  5.735782
16                          Lyon  45.757814  4.832011
17              Gorges du Verdon  43.749656  6.328562
18            Bormes les Mimosas  43.150697  6.341928
19                        Cassis  43.214036  5.539632
20                     Marseille  43.296399  5.377789
21               Aix en Provence  43.529842  5.447474
22                       Avignon  43.949249  4.805901
23                          Uzes  44.012128  4.419672
24                         Nimes  43.837425  4.360069
25                 Aigues Mortes  43.566152  4.191540
26      Saintes Maries de la mer  43.451592  4.427720
27                     Collioure  42.525050  3.083155
28                   Carcassonne  43.213036  2.349107
29                        Ariege  42.945537  1.406554
30                      Toulouse  43.604464  1.444243
31                     Montauban  44.017584  1.354999
32                      Biarritz  43.483252 -1.559278
33                       Bayonne  43.494514 -1.473666
34                   La Rochelle  46.159732 -1.151595

In [6]:
# Vérification : aucune ville sans coordonnées ?
missing = df_coords[df_coords["lat"].isna()]  # on utilise un mask -> un Df conditionné à l'intérieur d'un Df 
print(f"Villes sans coordonnées : {len(missing)}")
if len(missing) > 0:
    print(missing)

Villes sans coordonnées : 0

## 4. Prévisions météo via OpenWeatherMap

On utilise l'endpoint **`/data/2.5/forecast`** qui renvoie les prévisions sur **5 jours avec un pas de 3 heures** (donc 40 points par ville). C'est l'endpoint gratuit le plus riche — il ne nécessite pas de carte bancaire.

Paramètres clés :
- `lat`, `lon` : coordonnées de la ville
- `appid` : notre clé API
- `units=metric` : températures en °C
- `lang=fr` : descriptions météo en français

In [7]:
# On définit une fonction qui prend un couple de coordonnées d'une ville et renvoie une liste de 40 points de prévision sous forme de dict
OWM_URL = "https://api.openweathermap.org/data/2.5/forecast"

def get_forecast(lat: float, lon: float) -> list:
    """Retourne la liste brute des prévisions 3h sur 5 jours pour un point."""
    params = {
        "lat": lat,
        "lon": lon,
        "appid": OWM_API_KEY,
        "units": "metric",
        "lang": "fr",
    }
    response = requests.get(OWM_URL, params=params, timeout=10)
    response.raise_for_status()
    return response.json()["list"]  # liste de 40 prévisions hebdo (8 x 5j) pour une ville donnée 

# Test sur Paris
sample = get_forecast(48.8566, 2.3522)  # à quoi ressemble le format des prévisions pour UNE seule ville 
print(f"Nombre de points de prévision : {len(sample)}")
sample[0]  # on regarde UNE seule prévision parmi les 40 (8 x 5j)
            # et on ne met pas de print() à la dernière ligne d'une cellule de notebook jupiter, pas besoin, elle est automatiquement affichée

Nombre de points de prévision : 40

{'dt': 1782669600,
 'main': {'temp': 29.85,
  'feels_like': 29.99,
  'temp_min': 27.53,
  'temp_max': 29.85,
  'pressure': 1019,
  'sea_level': 1019,
  'grnd_level': 1010,
  'humidity': 44,
  'temp_kf': 2.32,
  'dew_point': 16.29},
 'weather': [{'id': 500,
   'main': 'Rain',
   'description': 'légère pluie',
   'icon': '10d'}],
 'clouds': {'all': 77},
 'wind': {'speed': 4.16, 'deg': 5, 'gust': 5.22},
 'visibility': 10000,
 'pop': 0.2,
 'rain': {'3h': 0.15},
 'sys': {'pod': 'd'},
 'dt_txt': '2026-06-28 18:00:00'}

### Agrégation des prévisions par ville

Chaque appel renvoie 40 points (5 jours × 8 points/jour). Pour scorer une ville, on résume ces 40 points en quelques indicateurs :
- **temp_avg** : température moyenne sur 5 jours (°C)
- **rain_total** : pluie cumulée sur 5 jours (mm)
- **clouds_avg** : couverture nuageuse moyenne (%)

In [8]:
# on définit une fonction qui prend une liste de 40 prévisions hebdo et retourne un dictionnaire d'indicateurs synthétiques
def summarize_forecast(forecast_list: list) -> dict:
    """Agrège une liste de 40 prévisions en quelques indicateurs synthétiques."""
    temps = [p["main"]["temp"] for p in forecast_list]  # list comprehension -> on prend la température (x40) 
    clouds = [p["clouds"]["all"] for p in forecast_list]   # on prend la couverture nuageuse (x40)
    # La pluie n'est présente dans le JSON que s'il pleut — d'où le .get()
    rain = [p.get("rain", {}).get("3h", 0) for p in forecast_list]   # on prend la pluie (x40)
    return {
        "temp_avg": round(sum(temps) / len(temps), 1),
        "rain_total": round(sum(rain), 1),
        "clouds_avg": round(sum(clouds) / len(clouds), 1),
    }

summarize_forecast(sample)

{'temp_avg': 23.3, 'rain_total': 1.0, 'clouds_avg': 37.6}

In [9]:
# On boucle sur toutes les villes qui ont des coordonnées
weather_data = []
for _, row in df_coords.iterrows():
    if pd.isna(row["lat"]):
        continue
    forecast = get_forecast(row["lat"], row["lon"])
    summary = summarize_forecast(forecast)
    weather_data.append({
        "city": row["city"],
        "lat": row["lat"],
        "lon": row["lon"],
        **summary,
    })
    # OpenWeatherMap autorise 60 req/min en gratuit : on est large, mais on reste propre
    time.sleep(0.2)

df_weather = pd.DataFrame(weather_data)
df_weather

,city,lat,lon,temp_avg,rain_total,clouds_avg
0,Mont Saint Michel,48.635954,-1.511460,17.3,0.0,47.0
1,Saint Malo,48.649518,-2.026041,17.1,0.0,54.0
2,Bayeux,49.276462,-0.702474,18.0,0.0,42.9
3,Le Havre,49.493898,0.107973,17.8,0.0,41.3
4,Rouen,49.440459,1.093966,19.7,0.0,42.6
5,Paris,48.858890,2.320041,23.3,1.0,37.6
6,Amiens,49.894171,2.295695,18.7,0.0,42.2
7,Lille,50.636565,3.063528,19.2,0.2,43.5
8,Strasbourg,48.584614,7.750713,24.0,11.7,49.4
9,Chateau du Haut Koenigsbourg,48.249382,7.343941,20.7,16.1,41.5
10,Colmar,48.077752,7.357964,23.6,14.2,45.2
11,Eguisheim,48.044797,7.307962,23.4,15.1,47.2
12,Besancon,47.238022,6.024362,23.3,2.2,45.4
13,Dijon,47.321581,5.041470,24.0,6.3,42.0
14,Annecy,45.899235,6.128885,23.6,11.2,44.0
15,Grenoble,45.187560,5.735782,24.9,5.5,41.5
16,Lyon,45.757814,4.832011,26.5,4.0,39.0
17,Gorges du Verdon,43.749656,6.328562,23.9,0.1,46.9
18,Bormes les Mimosas,43.150697,6.341928,26.5,0.1,29.2
19,Cassis,43.214036,5.539632,27.7,0.0,11.8
20,Marseille,43.296399,5.377789,28.8,0.0,11.2
21,Aix en Provence,43.529842,5.447474,29.7,0.1,20.6
22,Avignon,43.949249,4.805901,29.8,1.4,15.4
23,Uzes,44.012128,4.419672,28.8,2.1,16.1
24,Nimes,43.837425,4.360069,30.0,1.8,15.6
25,Aigues Mortes,43.566152,4.191540,29.0,0.2,17.2
26,Saintes Maries de la mer,43.451592,4.427720,28.3,0.0,11.7
27,Collioure,42.525050,3.083155,28.0,1.6,6.2
28,Carcassonne,43.213036,2.349107,25.2,7.6,29.5
29,Ariege,42.945537,1.406554,18.3,4.5,42.8
30,Toulouse,43.604464,1.444243,24.0,7.2,32.1
31,Montauban,44.017584,1.354999,23.7,25.5,31.7
32,Biarritz,43.483252,-1.559278,19.7,7.0,58.9
33,Bayonne,43.494514,-1.473666,19.8,7.1,58.5
34,La Rochelle,46.159732,-1.151595,20.2,0.0,27.3

In [10]:
sample = get_forecast(48.8566, 2.3522)  # Paris
print(f"Première prévision : {sample[0]['dt_txt']}")
print(f"Dernière prévision : {sample[-1]['dt_txt']}")
print(f"Nombre de points    : {len(sample)}")

Première prévision : 2026-06-28 18:00:00
Dernière prévision : 2026-07-03 15:00:00
Nombre de points    : 40

## 5. Calcul d'un score météo

On construit un score simple qui récompense la chaleur et pénalise la pluie et les nuages.
Formule choisie (arbitraire mais explicable) :

$$\text{score} = \text{temp\_avg} - 0.5 \times \text{rain\_total} - 0.1 \times \text{clouds\_avg}$$

Plus le score est élevé, plus la destination est attractive météo.

In [11]:
df_weather["weather_score"] = (
    df_weather["temp_avg"]
    - 0.5 * df_weather["rain_total"]
    - 0.1 * df_weather["clouds_avg"]
).round(2)

# Top 5 des destinations de la semaine
df_weather.sort_values("weather_score", ascending=False).head()

,city,lat,lon,temp_avg,rain_total,clouds_avg,weather_score
20,Marseille,43.296399,5.377789,28.8,0.0,11.2,27.68
21,Aix en Provence,43.529842,5.447474,29.7,0.1,20.6,27.59
22,Avignon,43.949249,4.805901,29.8,1.4,15.4,27.56
24,Nimes,43.837425,4.360069,30.0,1.8,15.6,27.54
25,Aigues Mortes,43.566152,4.191540,29.0,0.2,17.2,27.18

## 6. Sauvegarde

On sauvegarde le DataFrame en CSV pour éviter de relancer tous les appels API si on rouvre le notebook plus tard.

In [12]:
df_weather.to_csv("data/weather.csv", index=False)
print("✅ Données sauvegardées dans data/weather.csv")

✅ Données sauvegardées dans data/weather.csv